import { selectOfficialSetupScore } from './scoredDecision';
import type { SetupScore } from './setupScore';
import type { StrategyDecision } from './strategyDecision';
import type { TradePlan } from './tradePlan';
import type { PatienceFilterResult } from './patienceFilter';

const score = (direction: 'long' | 'short', total: number): SetupScore => ({ total, grade: total >= 80 ? 'A' : total >= 70 ? 'B' : 'D', categories: [], direction, status: 'available', sourceCandleTime: 't', reasons: [], warnings: [] });
const plan = (direction: 'long' | 'short'): TradePlan => ({ direction, status: 'ready', locationStatus: 'acceptable', confirmationStatus: 'confirmed', entryTrigger: '', entryPrice: 100, invalidationPrice: 96, stopPrice: 95, stopMethod: '', targets: [110], targetSource: 'structural', estimatedRewardRisk: 2, atrUsed: 1, sourceCandleTime: 't', reasons: [], warnings: [], missingInputs: [], structurallyInvalidated: false });
const patience = (direction: 'long' | 'short', status: PatienceFilterResult['status'] = 'allowed'): PatienceFilterResult => ({ direction, status, canEnter: status === 'allowed', blockingReasons: [], waitingReasons: [], passedChecks: [], failedChecks: [], missingInputs: [], sourceCandleTime: 't' });
const decision = (action: StrategyDecision['action'], direction: StrategyDecision['direction'] = 'long'): StrategyDecision => ({ action, direction, status: action === 'BUY' ? 'confirmed' : action === 'NO_TRADE' ? 'blocked' : 'waiting', bias: direction === 'short' ? 'bearish' : direction === 'long' ? 'bullish' : 'neutral', setupStatus: action === 'BUY' ? 'confirmed' : action === 'NO_TRADE' ? 'blocked' : action === 'WAIT_FOR_PULLBACK' ? 'waiting_for_pullback' : 'waiting_for_confirmation', sourceCandleTime: 't', entryTrigger: null, entryPrice: null, invalidationPrice: null, stopPrice: null, targets: [], estimatedRewardRisk: null, primaryReason: '', reasons: [], warnings: [], blockingReasons: [], waitingReasons: [], technicalContextStatus: 'ready', longPlanStatus: 'ready', shortPlanStatus: 'ready', longPatienceStatus: 'allowed', shortPatienceStatus: 'allowed' });
const input = (action: StrategyDecision['action'], direction: StrategyDecision['direction'] = 'long', long = 80, short = 60) => ({ decision: decision(action, direction), longScore: score('long', long), shortScore: score('short', short), longPlan: plan('long'), shortPlan: plan('short'), longPatience: patience('long'), shortPatience: patience('short') });

describe('scored decision', () => {
  it('selects directional scores for BUY, SELL, pullback, and next-close actions', () => { expect(selectOfficialSetupScore(input('BUY')).selectedDirection).toBe('long'); expect(selectOfficialSetupScore(input('SELL', 'short')).selectedDirection).toBe('short'); expect(selectOfficialSetupScore(input('WAIT_FOR_PULLBACK')).premiumSetupState).toBe('high_quality_forming'); expect(selectOfficialSetupScore(input('WAIT_FOR_NEXT_4H_CLOSE')).premiumSetupState).toBe('high_quality_waiting_confirmation'); });
  it('keeps NO_TRADE non-actionable and marks premium blocked separately', () => { const result = selectOfficialSetupScore(input('NO_TRADE', 'none')); expect(result).toMatchObject({ isActionable: false, premiumSetupState: 'high_quality_blocked' }); });
  it('uses higher score for neutral WAIT and never lets score override blocked gates', () => { const value = input('WAIT', 'none', 60, 75); value.longPatience = patience('long', 'blocked'); const result = selectOfficialSetupScore(value); expect(result.selectedDirection).toBe('short'); expect(result.isActionable).toBe(false); });
  it('is deterministic and immutable', () => { const value = input('BUY'); const before = structuredClone(value); expect(selectOfficialSetupScore(value)).toEqual(selectOfficialSetupScore(value)); expect(value).toEqual(before); });
});
