import { getTorontoScheduleSlot, parseSchedulerEnabled, parseSchedulerProvider } from './torontoSchedule';

/**
 * Dedicated coverage for the Toronto slot matcher and env parsers. Complements the
 * higher-level scheduler-lifecycle tests in fixtureScheduler.test.ts (which exercise
 * these functions incidentally) with direct boundary coverage: the Saturday/Sunday
 * exclusions each of the 6 daily slots depends on, off-by-a-minute times, and both
 * annual DST transitions. All UTC instants below were generated by scanning
 * Intl.DateTimeFormat({ timeZone: 'America/Toronto' }) output minute-by-minute in a
 * script rather than computed by hand, to avoid manual offset-arithmetic errors.
 */
describe('getTorontoScheduleSlot', () => {
  // Monday 2026-06-15, one UTC instant per slot (EDT, non-DST-transition week).
  const mondaySlots: { utc: string; time: string }[] = [
    { utc: '2026-06-15T05:01:00.000Z', time: '01:01' },
    { utc: '2026-06-15T09:01:00.000Z', time: '05:01' },
    { utc: '2026-06-15T13:01:00.000Z', time: '09:01' },
    { utc: '2026-06-15T17:01:00.000Z', time: '13:01' },
    { utc: '2026-06-15T21:01:00.000Z', time: '17:01' },
  ];

  it.each(mondaySlots)('matches Monday $time America/Toronto', ({ utc, time }) => {
    expect(getTorontoScheduleSlot(new Date(utc))).toMatchObject({ weekday: 'Monday', time });
  });

  it('matches Friday at 13:01', () => {
    expect(getTorontoScheduleSlot(new Date('2026-06-19T17:01:00.000Z'))).toMatchObject({ weekday: 'Friday', time: '13:01' });
  });

  // Saturday 2026-06-20 UTC instants for 01:01/05:01/09:01/13:01/17:01 (all must be excluded: market closed all day).
  const saturdayInstants = [
    '2026-06-20T05:01:00.000Z',
    '2026-06-20T09:01:00.000Z',
    '2026-06-20T13:01:00.000Z',
    '2026-06-20T17:01:00.000Z',
    '2026-06-20T21:01:00.000Z',
  ];

  it.each(saturdayInstants)('excludes Saturday slot at %s (market closed)', (utc) => {
    expect(getTorontoScheduleSlot(new Date(utc))).toBeNull();
  });

  // Sunday 2026-06-14 UTC instants for 01:01/05:01/09:01/13:01/17:01 (all fall before the 21:00 Sunday open).
  const sundayBeforeOpenInstants = [
    '2026-06-14T05:01:00.000Z',
    '2026-06-14T09:01:00.000Z',
    '2026-06-14T13:01:00.000Z',
    '2026-06-14T17:01:00.000Z',
    '2026-06-14T21:01:00.000Z',
  ];

  it.each(sundayBeforeOpenInstants)('excludes Sunday-before-open slot at %s', (utc) => {
    expect(getTorontoScheduleSlot(new Date(utc))).toBeNull();
  });

  it('matches Monday-Friday and Sunday at 21:01, but excludes Saturday 21:01', () => {
    expect(getTorontoScheduleSlot(new Date('2026-06-16T01:01:00.000Z'))).toMatchObject({ weekday: 'Monday', time: '21:01' });
    expect(getTorontoScheduleSlot(new Date('2026-06-15T01:01:00.000Z'))).toMatchObject({ weekday: 'Sunday', time: '21:01' });
    expect(getTorontoScheduleSlot(new Date('2026-06-21T01:01:00.000Z'))).toBeNull();
  });

  it('rejects times one minute before or after any slot', () => {
    for (const { utc } of mondaySlots) {
      const oneMinBefore = new Date(new Date(utc).getTime() - 60_000);
      const oneMinAfter = new Date(new Date(utc).getTime() + 60_000);
      expect(getTorontoScheduleSlot(oneMinBefore)).toBeNull();
      expect(getTorontoScheduleSlot(oneMinAfter)).toBeNull();
    }
  });

  it('produces a stable localDate/time key usable for slot dedup', () => {
    const slot = getTorontoScheduleSlot(new Date('2026-06-15T17:01:00.000Z'));
    expect(slot).toMatchObject({ key: '2026-06-15:13:01', localDate: '2026-06-15' });

    const earlySlot = getTorontoScheduleSlot(new Date('2026-06-15T09:01:00.000Z'));
    expect(earlySlot).toMatchObject({ key: '2026-06-15:05:01', localDate: '2026-06-15' });
  });

  it('uses Toronto daylight-saving offsets across both spring-forward and fall-back transitions', () => {
    // 21:01, kept from the original test (falls on a Sunday, valid for that slot).
    expect(getTorontoScheduleSlot(new Date('2026-03-09T01:01:00.000Z'))?.key).toBe('2026-03-08:21:01');
    expect(getTorontoScheduleSlot(new Date('2026-11-02T02:01:00.000Z'))?.key).toBe('2026-11-01:21:01');

    // Friday immediately before spring-forward (2026-03-06, still EST) — all 5 weekday slots.
    expect(getTorontoScheduleSlot(new Date('2026-03-06T06:01:00.000Z'))?.key).toBe('2026-03-06:01:01');
    expect(getTorontoScheduleSlot(new Date('2026-03-06T10:01:00.000Z'))?.key).toBe('2026-03-06:05:01');
    expect(getTorontoScheduleSlot(new Date('2026-03-06T14:01:00.000Z'))?.key).toBe('2026-03-06:09:01');
    expect(getTorontoScheduleSlot(new Date('2026-03-06T18:01:00.000Z'))?.key).toBe('2026-03-06:13:01');
    expect(getTorontoScheduleSlot(new Date('2026-03-06T22:01:00.000Z'))?.key).toBe('2026-03-06:17:01');

    // Monday immediately after spring-forward (2026-03-09, now EDT).
    expect(getTorontoScheduleSlot(new Date('2026-03-09T05:01:00.000Z'))?.key).toBe('2026-03-09:01:01');
    expect(getTorontoScheduleSlot(new Date('2026-03-09T09:01:00.000Z'))?.key).toBe('2026-03-09:05:01');
    expect(getTorontoScheduleSlot(new Date('2026-03-09T13:01:00.000Z'))?.key).toBe('2026-03-09:09:01');
    expect(getTorontoScheduleSlot(new Date('2026-03-09T17:01:00.000Z'))?.key).toBe('2026-03-09:13:01');
    expect(getTorontoScheduleSlot(new Date('2026-03-09T21:01:00.000Z'))?.key).toBe('2026-03-09:17:01');

    // Friday immediately before fall-back (2026-10-30, still EDT).
    expect(getTorontoScheduleSlot(new Date('2026-10-30T05:01:00.000Z'))?.key).toBe('2026-10-30:01:01');
    expect(getTorontoScheduleSlot(new Date('2026-10-30T09:01:00.000Z'))?.key).toBe('2026-10-30:05:01');
    expect(getTorontoScheduleSlot(new Date('2026-10-30T13:01:00.000Z'))?.key).toBe('2026-10-30:09:01');
    expect(getTorontoScheduleSlot(new Date('2026-10-30T17:01:00.000Z'))?.key).toBe('2026-10-30:13:01');
    expect(getTorontoScheduleSlot(new Date('2026-10-30T21:01:00.000Z'))?.key).toBe('2026-10-30:17:01');

    // Monday immediately after fall-back (2026-11-02, now EST).
    expect(getTorontoScheduleSlot(new Date('2026-11-02T06:01:00.000Z'))?.key).toBe('2026-11-02:01:01');
    expect(getTorontoScheduleSlot(new Date('2026-11-02T10:01:00.000Z'))?.key).toBe('2026-11-02:05:01');
    expect(getTorontoScheduleSlot(new Date('2026-11-02T14:01:00.000Z'))?.key).toBe('2026-11-02:09:01');
    expect(getTorontoScheduleSlot(new Date('2026-11-02T18:01:00.000Z'))?.key).toBe('2026-11-02:13:01');
    expect(getTorontoScheduleSlot(new Date('2026-11-02T22:01:00.000Z'))?.key).toBe('2026-11-02:17:01');
  });
});

describe('parseSchedulerEnabled', () => {
  it('defaults to enabled when unset', () => {
    expect(parseSchedulerEnabled(undefined)).toBe(true);
  });

  it('accepts explicit true/false', () => {
    expect(parseSchedulerEnabled('true')).toBe(true);
    expect(parseSchedulerEnabled('false')).toBe(false);
  });

  it('throws a descriptive error for any other value', () => {
    expect(() => parseSchedulerEnabled('1')).toThrow('NAS100_DASHBOARD_SCHEDULER_ENABLED must be "true" or "false".');
    expect(() => parseSchedulerEnabled('')).toThrow('NAS100_DASHBOARD_SCHEDULER_ENABLED');
  });
});

describe('parseSchedulerProvider', () => {
  it('defaults to fixture when unset', () => {
    expect(parseSchedulerProvider(undefined)).toBe('fixture');
  });

  it('accepts explicit fixture/oanda', () => {
    expect(parseSchedulerProvider('fixture')).toBe('fixture');
    expect(parseSchedulerProvider('oanda')).toBe('oanda');
  });

  it('throws a descriptive error for any other value', () => {
    expect(() => parseSchedulerProvider('live')).toThrow('NAS100_DASHBOARD_SCHEDULER_PROVIDER must be "fixture" or "oanda".');
  });
});
