import {
  ACTIONS,
  BIASES,
  CANDLE_STATUSES,
  CROSS_MARKET_INSTRUMENTS,
  CROSS_MARKET_CONFIRMATIONS,
  DAILY_REGIMES,
  DATA_FRESHNESS_STATES,
  DATA_HEALTH_STATES,
  EVENT_RISK_SEVERITIES,
  EVENT_RISK_STATUSES,
  H4_STRUCTURES,
  INSTRUMENT_CONFIRMATIONS,
  PROVIDER_STATUSES,
  SETUP_GRADES,
  SETUP_STATUSES,
  TIMEFRAMES,
  ZONE_TYPES,
  ActionSchema,
  BiasSchema,
  CandleStatusSchema,
  CrossMarketInstrumentSchema,
  CrossMarketConfirmationSchema,
  DailyRegimeSchema,
  DataFreshnessSchema,
  DataHealthStatusSchema,
  EventRiskSeveritySchema,
  EventRiskStatusSchema,
  H4StructureSchema,
  InstrumentConfirmationSchema,
  ProviderStatusSchema,
  SetupGradeSchema,
  SetupStatusSchema,
  TimeframeSchema,
  ZoneTypeSchema,
} from './enums';

describe('central domain enums', () => {
  it.each([
    ['action', ACTIONS, ActionSchema],
    ['setup status', SETUP_STATUSES, SetupStatusSchema],
    ['bias', BIASES, BiasSchema],
    ['daily regime', DAILY_REGIMES, DailyRegimeSchema],
    ['H4 structure', H4_STRUCTURES, H4StructureSchema],
    ['candle status', CANDLE_STATUSES, CandleStatusSchema],
    ['freshness', DATA_FRESHNESS_STATES, DataFreshnessSchema],
    ['data health', DATA_HEALTH_STATES, DataHealthStatusSchema],
    ['provider status', PROVIDER_STATUSES, ProviderStatusSchema],
    ['event severity', EVENT_RISK_SEVERITIES, EventRiskSeveritySchema],
    ['event status', EVENT_RISK_STATUSES, EventRiskStatusSchema],
    ['zone type', ZONE_TYPES, ZoneTypeSchema],
    ['setup grade', SETUP_GRADES, SetupGradeSchema],
    ['cross-market instrument', CROSS_MARKET_INSTRUMENTS, CrossMarketInstrumentSchema],
    ['cross-market confirmation', CROSS_MARKET_CONFIRMATIONS, CrossMarketConfirmationSchema],
    ['instrument confirmation', INSTRUMENT_CONFIRMATIONS, InstrumentConfirmationSchema],
    ['timeframe', TIMEFRAMES, TimeframeSchema],
  ] as const)('accepts every %s enum value and rejects unknown values', (_name, values, schema) => {
    values.forEach((value) => expect(schema.safeParse(value).success).toBe(true));
    expect(schema.safeParse('NOT_A_DOMAIN_VALUE').success).toBe(false);
  });
});
